version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ordinals_api_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"

  ord:
    image: bentatum/ord:dev
    command: "--rpc-url ${APP_BITCOIN_NODE_IP} --index-sats --chain ${APP_BITCOIN_NETWORK} index"
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/ord
      - ${APP_BITCOIN_DATA_DIR}:/root/.bitcoin:ro

  api:
    image: bentatum/ord-api:dev
    ports:
      - "3000:3000"
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/ord
      - ${APP_BITCOIN_DATA_DIR}:/root/.bitcoin:ro
    environment:
      - RPC_URL=${APP_BITCOIN_NODE_IP}
      - CHAIN=${APP_BITCOIN_NETWORK}

