version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ordinals_web_1
      APP_PORT: 6942

  ord:
    image: bentatum/ord:dev
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/ord
      - ${APP_BITCOIN_DATA_DIR}:/root/.bitcoin:ro
