version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ordinals_web_1
      APP_PORT: 3000

  ord:
    image: bentatum/ord:dev
    ports:
      - "3000:3000"
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/ord
      - ${APP_BITCOIN_DATA_DIR}:/root/.bitcoin:ro
