version: "3.7"

services:
  app_proxy:
    environment:
      KEEP: "true"

  ord:
    image: bentatum/ord:dev
    restart: on-failure
    ports:
      - ${APP_BITCOIN_RPC_PORT}:${APP_BITCOIN_RPC_PORT}
    volumes:
      - ${APP_BITCOIN_DATA_DIR}:/root/.bitcoin:ro
    environment:
      BITCOIN_RPC_HOST: "$APP_BITCOIN_NODE_IP"
      BITCOIN_RPC_PORT: "$APP_BITCOIN_RPC_PORT"
