version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ordinals_ord_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"

  ord:
    image: bentatum/ord:dev
    command: "--rpc-url ${APP_BITCOIN_NODE_IP} --index-sats --chain ${APP_BITCOIN_NETWORK} server --http"
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/ord
      - ${APP_BITCOIN_DATA_DIR}:/root/.bitcoin:ro
